### ISSUE TITLE
Strange behaviour with remote images.

### ISSUE THREAD

**Issue by yop289** [evgenyneu/Auk#25] opened 2016-05-20 20:37 UTC
Hi 

First incredible library, I was doing some testing and I have found some strange behaviour. 

1) I click on remote the images append perfect at scrollview but when I scroll it I see and animation from placeholder image to downloaded image ( even if the image is cached).
2) If I scroll back and scroll again the fade effect disappear.

It looks strange behaviour when local images and remote are both in the slider the local images do not reproduce the fade effect and the remote images yes (but only the first time)

I hope I have explained.

Best regards
David

**Comment by evgenyneu** [comment] 2016-05-20 21:15
Hi @yop289, thanks for your feedback. I know it may look confusing, but this is an expected behaviour and here is why.

The Moa downloader uses NSUrlSession for caching remote image. It requests a file from the NSUrlSession and supplies a result callback. The problem is that it does not know if the image came immediately from the cache or the network (maybe there is a way to know that?).

```Swift
session.dataTaskWithURL("https://site.com/bird.jpg") { (data, response, error) in
   // Data received (or error)
} 
```

As you noticed, Auk always creates a fade-in effect for remote images. And because it does not know if the image came from cache it fades-in all remote images. But once the image is loaded into the scroll view it stays there, that's why you do not see the fade-in the second time you scroll onto the image.

I hope my explanation wasn't very confusing. Regards.

**Comment by yop289** [comment] 2016-05-23 12:25
Hi

Thanks for response, you are right indeed I have seen some apps with slide show and all have the same effect,  I have another question, I want to save permanently the images downloaded using NSFileManager, can you tell me where will be the best place to implement this code, I was thinking to do it inside the method downloadImage at AukRemoteImage class, or maybe I must do it on moa class?

Best regards

**Comment by evgenyneu** [comment] 2016-05-23 21:32
Hi, yes, you can save the image when in arrives in AukRemoteImage call, in didReceiveImageAsync, for example.

**Comment by evgenyneu** [comment] 2016-05-29 22:46
Closing this issue, feel free to reopen when needed.

**Closed by evgenyneu** 2016-05-29 22:46 UTC
