### ISSUE TITLE
single image,not downloaded from url

### ISSUE THREAD

**Issue by farshadjahanmanesh** [evgenyneu/Auk#46] opened 2016-08-28 16:45 UTC
hi, maybe its weird or there is something that i dont know about auks settings...
but when there is just one image in the slider, library doesn't download it... i am using it to show products images, but some of them has only one image, for this products, slider wouldn't download that one

**Comment by evgenyneu** [comment] 2016-08-28 21:13
Hi, @farshadjahanmanesh, thank you for bringing it up. Could you give a URL to the image so I can try it?

**Comment by farshadjahanmanesh** [comment] 2016-08-29 02:54
yeah sure
here you are,
http://solooxygen.ir/host/solooxygen/rescue/sol/Emergency/1.jpg

i tested it, when there is just one image, slider wouldn't download it, but i added same image for two times in slider array, and it worked

`  func bindImages(){
        img_slider.auk.settings.placeholderImage = UIImage.PlaceHolder()
        img_slider.auk.settings.pagingEnabled = true
        img_slider.auk.settings.showsHorizontalScrollIndicator = true
        if (sliderType == SliderType.HomePage.rawValue)
        {
            img_slider.auk.settings.contentMode = UIViewContentMode.ScaleAspectFill
        }else{
            img_slider.auk.settings.contentMode = UIViewContentMode.ScaleAspectFit
        
        }
        img_slider.auk.settings.preloadRemoteImagesAround = 2
        img_slider.auk.startAutoScroll(delaySeconds: 5)
        for slide in Slides {
            img_slider.auk.show(url: slide.image)
        }
        if let cb = callback
        {cb(complete: img_slider)}
        loadingDismis()
    }
`

`  static func GetSliderFormat(slides : [ProductSlides])->[SliderModel]?{
        var list=[SliderModel]()
        
        for item in slides {
            let newmodel=SliderModel()
            newmodel.image=item.image
//this line, same image added to array two times and slider worked
            list.append(newmodel)
            list.append(newmodel)
        }
        
        if(list.count==0){
            return nil
        }
        return list
    }
`

**Comment by farshadjahanmanesh** [comment] 2016-08-30 06:40
yeah sure
here you are,
http://solooxygen.ir/host/solooxygen/rescue/sol/Emergency/1.jpg

i tested it, when there is just one image, slider wouldn't download it, but i added same image for two times in slider array, and it worked

`  
func bindImages(){
        img_slider.auk.settings.placeholderImage = UIImage.PlaceHolder()
        img_slider.auk.settings.pagingEnabled = true
        img_slider.auk.settings.showsHorizontalScrollIndicator = true
        if (sliderType == SliderType.HomePage.rawValue)
        {
            img_slider.auk.settings.contentMode = UIViewContentMode.ScaleAspectFill
        }else{
            img_slider.auk.settings.contentMode = UIViewContentMode.ScaleAspectFit
        
        }
        img_slider.auk.settings.preloadRemoteImagesAround = 2
        img_slider.auk.startAutoScroll(delaySeconds: 5)
        for slide in Slides {
            img_slider.auk.show(url: slide.image)
        }
        if let cb = callback
        {cb(complete: img_slider)}
        loadingDismis()
    }
`

` 
 static func GetSliderFormat(slides : [ProductSlides])->[SliderModel]?{
        var list=[SliderModel]()
        
        for item in slides {
            let newmodel=SliderModel()
            newmodel.image=item.image
//this line, same image added to array two times and slider worked
            list.append(newmodel)
            list.append(newmodel)
        }
        
        if(list.count==0){
            return nil
        }
        return list
    }
`

**Comment by evgenyneu** [comment] 2016-09-03 23:59
Hello @farshadjahanmanesh, thanks for the example code. I could not reproduce this issue, unfortunately. I have created a demo app with it and it works for me both on an iOS 9 device and in the iOS 10 simulator. Here is the Xcode 8 beta 6 project. Do you think there are other factors that may be causing this problem?

[UsingAuk.zip](https://github.com/evgenyneu/Auk/files/453689/UsingAuk.zip)

**Comment by farshadjahanmanesh** [comment] 2016-09-04 16:23
thanks for your supports... maybe its because that i've used older version of AUK, now i have added 
pod 'moa', git: 'https://github.com/evgenyneu/moa.git', tag: '8.0.0'
pod 'Auk', git: 'https://github.com/evgenyneu/Auk.git', tag: '6.0.0'

to my pod and install them
and i am getting about 36 errors regarding to moa ....
please look at this image http://www.farshadjahanmanesh.ir/host/jahanmanesh/Untit3led1.jpg

**Comment by farshadjahanmanesh** [comment] 2016-09-04 19:18
thanks for your supporting... hum, i think this issue is because that i am using old version, pod 'Auk', '~> 2.1' ... i afraid of migrating to swift 3

**Comment by evgenyneu** [comment] 2016-09-04 21:03
No worries, let me know if you can find a solution to this. It may still be an issue with the library, it is just that I could not reproduce it in my environment.

**Comment by evgenyneu** [comment] 2016-11-23 22:21
Closing the issue, feel free to reopen if needed.

**Comment by masbenx** [comment] 2017-01-16 09:22
sorry to reopen this..

when I use 
`scrollview.auk.settings.contentMode = .scaleAspectFill`
one image last always gone

but when i disable contentMode, all image can load without resizing.

**Comment by evgenyneu** [comment] 2017-01-16 09:56
Thanks for letting me know @masbenx, do you mean that last image is not shown?

Could you give me URLs to the images so I can test them?

**Comment by evgenyneu** [comment] 2017-01-21 00:18
@masbenx, I created a demo app that uses  `.scaleAspectFill` content mode and shows two remote images. The second images shows up for me, so I could not reproduce your problem. Am I missing something?

Please find the demo project attached.
[AukScaleAspectFill.zip](https://github.com/evgenyneu/Auk/files/720773/AukScaleAspectFill.zip)

**Comment by evgenyneu** [comment] 2017-07-08 00:11
Closing the issue, feel free to reopen if needed.

**Closed by evgenyneu** 2017-07-08 00:11 UTC
